### ISSUE TITLE
How to access the Token Auth Method (API)?

### ISSUE THREAD

**Issue by XSven** [ByteFoundryAU/perl-WebService-HashiCorp-Vault#5]
It is unclear to me which class of the WebService-HashiCorp-Vault distribution has to be used to access

[Token Auth Method (API)](https://www.vaultproject.io/api-docs/auth/token#token-auth-method-api)

In particular I want to check the validity of an authentication token with GET /auth/token/lookup-self.

**Comment by djzort** [comment]
It's not currently supported. It should be fairly trivial to add and I welcome PR's
